In [1]:
import numpy as np

In [3]:
arr1 = np.array([[1,2,3], [4,5,6]], dtype ='float')
print("arr1: {}".format(arr1))

arr1: [[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
arr2 = np.array((1,2,3))
print("arr2: {}".format(arr2))

arr2: [1 2 3]


In [7]:
arr3 = np.zeros((2,3))
print("Initialized zero arrays with 2*3: {}".format(arr3))

Initialized zero arrays with 2*3: [[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
arr4 = np.arange(0,20,2)
print("Generate 0 to 20 by ranging 2: {}".format(arr4))

Generate 0 to 20 by ranging 2: [ 0  2  4  6  8 10 12 14 16 18]


In [11]:
arr5 = np.linspace(0,10,20)
print("Arr5: {}".format(arr5))

Arr5: [ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [12]:
arr6 = np.arange(0,15).reshape(3,5)
print("arr6: {}".format(arr6))

arr6: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [19]:
arr7 = np.arange(0,18).reshape(6,3)
print("arr7: {}".format(arr7))

arr7: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
